spring.application.name=suficiencia-avanzado

# MYSQL
# spring.datasource.url=${SPRING_DATASOURCE_URL}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Variables de prueba (ejemplo local MySQL)
spring.datasource.url=jdbc:mysql://junction.proxy.rlwy.net:20500/railway
spring.datasource.username=root
spring.datasource.password=wMQqDKvZNgGdSkrjhZgsDHWANNKkTQxp

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# THYMELEAF
spring.thymeleaf.cache=false

# PUERTO WEB DE SPRING
server.port=${PORT:8081}



# Tamaño máximo permitido por archivo para subidas
spring.servlet.multipart.max-file-size=20MB
# Tamaño máximo total por petición (incluye todos los archivos enviados)
spring.servlet.multipart.max-request-size=20MB